services:
  - type: web
    name: convertly-web
    runtime: docker
    plan: free
    region: oregon
    dockerfilePath: ./Dockerfile
    envVars:
      - key: ANTHROPIC_API_KEY
        sync: false
      - key: PAYPAL_CLIENT_ID
        sync: false
      - key: PAYPAL_CLIENT_SECRET
        sync: false
      - key: PAYPAL_MODE
        sync: false
      - key: PAYPAL_PRICE_USD
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: SESSION_COOKIE_SECURE
        sync: false
      - key: VOUCHER_CODES
        sync: false
      - key: MYMEMORY_EMAIL
        sync: false
      - key: FLASK_ENV
        sync: false
